### ISSUE TITLE
Open a bank account for the foundation

### ISSUE THREAD

**Issue by Hywan** [hoaproject/ActionBoard#14]
We need a bank account for the foundation.
#### Tasks
- [x] Open a bank account for the foundation,
- [ ] Get a credit card,
- [ ] Get online listings and actions.

**Comment by osaris** [comment]
I remembered that my sister told me that his bank (Credit Agricole) can open a bank account for an association with no fee if we have no credit authorized. I asked her few precisions right now but if we can open a bank account for the association (not with my name) it'll be easier for the future (what happens when the treasurer change ?).

I'll keep you informed.

**Comment by Hywan** [comment]
No credit card? That's blocking, isn't it?

**Comment by osaris** [comment]
No credit.

**Comment by osaris** [comment]
Overdraft ?

**Comment by Hywan** [comment]
@osaris I would prefer to avoid :-/.

**Comment by osaris** [comment]
@Hywan sorry, I mean "no credit authorized" means "no overdraft authorized" so what is the problem ?

**Comment by Hywan** [comment]
Oh ok. I understood no credit card. So everything is fine :-). No overdraft.

**Comment by osaris** [comment]
So here are the news from my sister working @CreditAgricole. We can have an account for the foundation (not at my name, at the name of the foundation). There is no fee for the account and ebanking. There is a 45.60€ per year fee for a Mastercard for online payment.

I think that its a good solution because :
- the account is at the name of the foundation (so no problem if somebody else is the treasurer etc)
- my sister can handle the opening for us and we can send her email if needed, that's a real + if you compare to whats happens to our file at the first bank we contacted
- I'm pretty sure that no bank will offer the mastercard/visa fees for a foundation

**Comment by Hywan** [comment]
👍👍👍

**Comment by osaris** [comment]
So ? :)

**Comment by Hywan** [comment]
Go :-).

**Comment by osaris** [comment]
Let's go !

**Comment by Hywan** [comment]
I receive all the required document list. Will take few days before gathering everything.

**Comment by osaris** [comment]
FYI, documents have been transmitted to the bank 2 weeks ago, we are waiting for their feedback.

**Comment by Hywan** [comment]
@osaris Excellent :-).

**Comment by osaris** [comment]
I have pinged my contact at the bank because I have no news and I assume you neither ?

**Comment by osaris** [comment]
Just sayin' https://number26.eu

**Comment by Hywan** [comment]
https://twitter.com/mnt_io/status/729937322154799104 waiting for feedbacks

**Comment by osaris** [comment]
So, as discussed at the today's hoa virtual meeting, we go with number26.eu to tackle this issue ! Stay tuned.

**Comment by osaris** [comment]
For France :

> We're temporarily backed-up in the opening of new accounts in your country. But we've added you to our wait list and will send you another email as soon as we have a further update. We very much appreciate your understanding in the meantime.

For Switzerland :

> At the moment we are only available in Austria, France, Greece, Germany, Ireland, Italy, Spain and Slovakia. We will keep you up to date and get in touch with you as soon as NUMBER26 is available in your country.

Wait & see !

**Comment by Hywan** [comment]
OK, so wait and see for France. Thank you very much!

**Comment by osaris** [comment]
Received yesterday by email :

> You've been more than patient as our new account wait list has been in place. We wanted to let you know that we expect to have more concrete information by mid-July regarding the resumption of new accounts in France.

**Comment by Hywan** [comment]
Crazy. Thanks for the feedback.

**Comment by osaris** [comment]
Received today by email :

> All of you will be able to sign up for an account in November. We realize this is a long time to wait, and we do sincerely apologize. We're doing everything we can in the meantime to add new features and services, and we hope that you'll find that it was worth the wait. 
> 
> Earlier this week we achieved official recognition as a licensed bank by the European Central Bank, which means we can power our product with our own bank throughout Europe. In the spirit of reducing complexity, we're also simplifying our brand. We're now officially called N26, and you can see our new logo above.

**Comment by Jir4** [comment]
I'm waiting too ^^

**Comment by osaris** [comment]
> Hey,
> 
> Good news: final preparations for you to join N26 Bank are almost complete. Thanks for your patience since you signed up for our waiting list.
> 
> We’ll send you an email this week with directions about how to open your N26 bank account.
> 
> If you successfully verify your identity before 30 November 2016, you will get your N26 account and Mastercard for free. It’s exactly what you wanted when you first joined our waiting list.
> 
> If you verify your identity after that date, you will get your N26 account for free, and you can add the Mastercard as an option for €2,90/month or €29/year based on our new policy for users outside of Germany and Austria.

**Comment by Hywan** [comment]
Go go go!

To be frank, I have almost forget this topic :-p.

**Comment by osaris** [comment]
Email to open the N26 account received today, I'll finalize the process in the following days so we have a Mastercard for free. Stay tuned !

**Comment by Hywan** [comment]
🎉

**Comment by osaris** [comment]
All done, I'll receive the mastercard in the next 2 weeks. We have a bank account (at my name...).

**Comment by Hywan** [comment]
🤑 🤑 💸 💰 💵 💰 💸 🤑 🤑 

MAKE CONTRIBUTORS PAY!
