### ISSUE TITLE
Shops to sell goodies

### ISSUE THREAD

**Issue by Hywan** [hoaproject/ActionBoard#16]
We need to sell goodies. We do not want to host a selling application. We need to find one or many shops online to sell goodies.
#### Tasks
- [x] Open shops to sell goodies,
- [x] Define at least 1 goody per shop,
- [x] List shops on the website.

**Comment by Hywan** [comment]
I am planning to open 2 shops:
- UnixStickers,
- Spreadshirt.

**Comment by Jir4** [comment]
I agree with both

**Comment by thehawk970** [comment]
me too

**Comment by Hywan** [comment]
# UnixStickers

http://www.unixstickers.com/tag/hoa

<img width="570" alt="screen shot 2015-10-27 at 16 27 29" src="https://cloud.githubusercontent.com/assets/946104/10762766/a5c1406e-7cc7-11e5-9fe0-8a599dcbe70b.png">

# SpreadShirt

https://shop.spreadshirt.fr/hoaproject (products may appear in a couple of hours)

<img width="315" alt="screen shot 2015-10-27 at 16 28 32" src="https://cloud.githubusercontent.com/assets/946104/10762798/caaa6ed2-7cc7-11e5-84f9-702af9207034.png">
<img width="327" alt="screen shot 2015-10-27 at 16 28 23" src="https://cloud.githubusercontent.com/assets/946104/10762802/cd2113c8-7cc7-11e5-96f6-acffe757a2d8.png">

**Comment by Jir4** [comment]
Did hoa get a tip on each sales ?

**Comment by Hywan** [comment]
@Jir4 According to the shop, yes. For UnixStickers, we don't get anything. However, they send us stickers when we need some of them. For SpreadShirt, I have declared a tip of 5€ per product.

**Comment by Hywan** [comment]
@osaris For SpreadShirt, for the bill, I use your names and postal address, since you're the treasurer of the foundation. Do you agree?

**Comment by Hywan** [comment]
@osaris Forget what I said.

I have created a `foundation@` email redirection (to mine), and I set the legal information of our SpreadShirt's shop to the foundation name and postal address.

**Comment by Jir4** [comment]
The foundation postal address is the @CircleCode one isn't it ?  I remember something like a move.

**Comment by Hywan** [comment]
@Jir4 Yes, we use its postal address. And yes, he is moving, so we must remind to update several references.

**Comment by Jir4** [comment]
:+1: so now we have a reminder in this topic \o/

**Comment by Hywan** [comment]
http://hoa-project.com/ is live.

**Comment by Hywan** [comment]
Done!

**Comment by Hywan** [comment]
Announce: https://twitter.com/hoaproject/status/663624587045900289.
